const value13 = {value: 13, left: undefined, right: undefined};
const value14 = {value: 14, left: value13, right: undefined};
const value7 = {value: 7, left: undefined, right: undefined};
const value4 = {value: 4, left: undefined, right: undefined};
const value6 = {value: 6, left: value4, right: value7};
const value1 = {value: 1, left: undefined, right: undefined};
const value3 = {value: 3, left: value1, right: value6};
const value10 = {value: 10, left: undefined, right: value14};
export const testTree = {value: 8, left: value3, right: value10};
